INSERT INTO department_ranks (department_id, code, name, level_order, description)
VALUES
((SELECT id FROM departments WHERE code = 'CAB'), 'CENTRAL_ADMINISTRATION_OFFICER', '중앙행정국원', 4, 'Level-4. Central Administration Officer. 중앙행정국의 행정 실무, 공식 기록 처리, 내부 명령 전달을 담당한다.'),
((SELECT id FROM departments WHERE code = 'CAB'), 'CENTRAL_ADMINISTRATION_DIRECTOR', '중앙행정국장', 5, 'Level-5. Central Administration Director. 중앙행정국의 최고 책임자로 행정 체계와 공식 기록 권한을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'CAB'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 부서 권한을 초월해 고위 감독과 최종 승인 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'CIA'), 'CAUSAL_INTELLIGENCE_AGENT', '정보요원', 1, 'Level-1. Causal Intelligence Agent. 인과 정보국의 시간선 정보 수집, 기록 대조, ERROR 전조 보고를 수행한다.'),
((SELECT id FROM departments WHERE code = 'CIA'), 'SENIOR_CAUSAL_INTELLIGENCE_AGENT', '선임 정보요원', 2, 'Level-2. Senior Causal Intelligence Agent. 숙련 정보요원으로 복합 시간선 정보와 현장 보고를 분석한다.'),
((SELECT id FROM departments WHERE code = 'CIA'), 'CAUSAL_INTELLIGENCE_OPERATIONS_CHIEF', '정보팀 작전과장', 3, 'Level-3. Causal Intelligence Operations Chief. 인과 정보팀 작전 단위를 지휘하고 분석 결과를 작전 계획으로 전환한다.'),
((SELECT id FROM departments WHERE code = 'CIA'), 'DEPUTY_CAUSAL_INTELLIGENCE_DIRECTOR', '인과 정보국 부국장', 4, 'Level-4. Deputy Causal Intelligence Director. 인과 정보국의 고위 책임자로 주요 정보 작전과 보고 체계를 관리한다.'),
((SELECT id FROM departments WHERE code = 'CIA'), 'CAUSAL_INTELLIGENCE_DIRECTOR', '인과 정보국 국장', 5, 'Level-5. Causal Intelligence Director. 인과 정보국의 최고 책임자로 정보 접근 권한과 분석 정책을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'CIA'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 인과 정보국 작전과 고위 인과 판단에 대한 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'BLB'), 'INTERN', '인턴', 0, 'Level-0. Intern. 경계교섭국의 기초 문서 정리, 현장 보조, 교섭 기록 지원을 담당한다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'BORDER_LIAISON_AGENT', '경계교섭요원', 1, 'Level-1. Border Liaison Agent. 경계 지역 접촉과 기본 교섭 절차를 수행한다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'SENIOR_LIAISON_AGENT', '상급교섭요원', 2, 'Level-2. Senior Liaison Agent. 복합 경계 사안과 위험 교섭 상황을 처리하는 숙련 요원이다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'BORDER_LIAISON_SUPERVISOR', '경계교섭 감독관', 3, 'Level-3. Border Liaison Supervisor. 교섭팀 현장 운영과 경계 대응 절차를 감독한다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'BORDER_LIAISON_COORDINATOR', '경계교섭 총괄관', 4, 'Level-4. Border Liaison Coordinator. 주요 경계교섭 작전과 다부서 조율을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'BORDER_LIAISON_DIRECTOR', '경계교섭 국장', 5, 'Level-5. Border Liaison Director. 경계교섭국의 최고 책임자로 대외 접촉 정책을 관리한다.'),
((SELECT id FROM departments WHERE code = 'BLB'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 경계교섭 사안의 최종 감독과 고위 승인 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'IAD'), 'AUDIT_AGENT', '감찰요원', 1, 'Level-1. Audit Agent. 내부 규정 위반, 권한 남용, 기록 이상에 대한 기본 조사를 수행한다.'),
((SELECT id FROM departments WHERE code = 'IAD'), 'SENIOR_AUDIT_AGENT', '선임 감찰요원', 2, 'Level-2. Senior Audit Agent. 복합 내부 사건과 고위 접근 기록을 조사하는 숙련 감찰요원이다.'),
((SELECT id FROM departments WHERE code = 'IAD'), 'AUDIT_TEAM_DIRECTOR', '감찰팀 이사장', 3, 'Level-3. Audit Team Director. 감찰팀 조사 방향과 내부 통제 절차를 지휘한다.'),
((SELECT id FROM departments WHERE code = 'IAD'), 'DEPUTY_INTERNAL_AUDIT_DIRECTOR', '내부감찰 부국장', 4, 'Level-4. Deputy Internal Audit Director. 내부 감찰 작전과 고위 조사 권한을 관리한다.'),
((SELECT id FROM departments WHERE code = 'IAD'), 'INTERNAL_AUDIT_DIRECTOR', '내부감찰 국장', 5, 'Level-5. Internal Audit Director. 내부 감찰부의 최고 책임자로 감찰 정책과 징계 보고를 총괄한다.'),
((SELECT id FROM departments WHERE code = 'IAD'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 감찰 사안의 최종 감독과 예외 승인 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'ISA'), 'JUNIOR_GUARD', '초급 경비병', 0, 'Level-0. Junior Guard. 시설 출입 통제와 기본 순찰을 수행하는 기초 보안 인원이다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'INTERMEDIATE_GUARD', '중급 경비병', 1, 'Level-1. Intermediate Guard. 표준 보안 임무와 격리구역 경비를 수행한다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'SENIOR_GUARD', '상급 경비병', 2, 'Level-2. Senior Guard. 위험 시설 경비와 보안 이상 상황 대응을 담당한다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'SECURITY_ADJUTANT', '보안 부관', 3, 'Level-3. Security Adjutant. 보안 작전 보조 지휘와 현장 보고 체계를 관리한다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'SECURITY_BATTALION_COMMANDER', '보안 대대장', 4, 'Level-4. Security Battalion Commander. 시설 보안 병력과 방어 작전을 지휘한다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'FACILITY_SECURITY_SUPERVISOR', '시설 보안국 감독관', 5, 'Level-5. Facility Security Supervisor. 시설 보안국의 최고 현장 책임자로 전체 보안 체계를 감독한다.'),
((SELECT id FROM departments WHERE code = 'ISA'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 시설 보안 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'NRD'), 'RESEARCH_INTERN', '연구 인턴', 0, 'Level-0. Research Intern. 서사학 연구 자료 정리와 실험 보조를 수행한다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'ASSISTANT_RESEARCHER', '보조 연구원', 1, 'Level-1. Assistant Researcher. 기초 서사 자료 분석과 연구 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'FIELD_RESEARCHER', '현장 연구원', 2, 'Level-2. Field Researcher. 현장 서사 현상 관측과 실험 기록을 수행한다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'SENIOR_RESEARCHER', '선임 연구원', 3, 'Level-3. Senior Researcher. 연구 프로젝트의 실무 책임자로 분석과 실험 방향을 조율한다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'DOCTOR', '박사', 4, 'Level-4. Doctor. 고위 연구자로 서사학 이론, 격리 가설, 실험 설계를 담당한다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'NARRATOLOGY_RESEARCH_HEAD', '서사학 연구부서장', 5, 'Level-5. Narratology Research Head. 서사학 연구부의 최고 책임자로 연구 정책과 승인 권한을 가진다.'),
((SELECT id FROM departments WHERE code = 'NRD'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 서사 연구의 고위 감독과 최종 승인 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'STRC'), 'SPECIAL_TASK_OPERATIVE', '특무부대원', 1, 'Level-1. Special Task Operative. 특수 대응 작전의 기본 임무를 수행한다.'),
((SELECT id FROM departments WHERE code = 'STRC'), 'SENIOR_SPECIAL_TASK_OPERATIVE', '선임 특무부대원', 2, 'Level-2. Senior Special Task Operative. 고위험 현장 대응과 소규모 작전 수행을 담당한다.'),
((SELECT id FROM departments WHERE code = 'STRC'), 'SPECIAL_TASK_NCO', '특무부대 부사관', 3, 'Level-3. Special Task Noncommissioned Officer. 특무부대 분대 지휘와 현장 작전 통제를 수행한다.'),
((SELECT id FROM departments WHERE code = 'STRC'), 'SPECIAL_TASK_UNIT_COMMANDER', '특무부대장', 4, 'Level-4. Special Task Unit Commander. 특무부대 작전 단위를 지휘하고 위험 대응 계획을 승인한다.'),
((SELECT id FROM departments WHERE code = 'STRC'), 'SPECIAL_RESPONSE_TEAM_COMMANDER', '특무대응팀 사령관', 5, 'Level-5. Special Response Team Commander. 특무대응사령부의 최고 작전 책임자다.'),
((SELECT id FROM departments WHERE code = 'STRC'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 특무 작전의 최종 감독과 예외 교전 승인 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_TECHNICAL_TRAINEE', '기술 실습원', 0, 'Level-0. Matrix Technical Trainee. 매트릭스공학지원부의 기술 정비, 장비 점검, 설비 기록 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_FACILITY_MAINTENANCE_OFFICER', '설비 관리원', 1, 'Level-1. Matrix Facility Maintenance Officer. 재단 물리 시설과 전술 장비의 정기 유지보수를 수행한다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_ENGINEERING_TACTICS_OFFICER', '공학 전술관', 2, 'Level-2. Matrix Engineering Tactics Officer. 작전 환경에 필요한 다중우주 통신 장비와 기술 대응을 담당한다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_PUBLIC_WORKS_SUPERVISOR', '공무감독관', 3, 'Level-3. Matrix Public Works Supervisor. 공학 작업 단위와 ERROR 격리 설비 보수 계획을 감독한다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_CAUSAL_DESIGN_MANAGER', '인과설계관리관', 4, 'Level-4. Matrix Causal Design Manager. 시간선 관측 장비와 인과 기반 설계의 고위 관리 책임자다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'MATRIX_ENGINEERING_SUPPORT_HEAD', '매트릭스공학지원부서장', 5, 'Level-5. Matrix Engineering Support Head. 매트릭스공학지원부의 최고 책임자로 시설 기술 정책을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'CME'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 매트릭스공학지원부 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_MEDICAL_INTERN', '인턴', 0, 'Level-0. Cognitive Medical Intern. 인지재구성의료부서의 의료 기록 보조와 기본 처치 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_MEDICAL_RESIDENT', '레지던트', 1, 'Level-1. Cognitive Medical Resident. 신체 질환 치료와 환자 관찰을 수행하는 정식 의료 인원이다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_MEDICAL_ASSISTANT', '의료 보조사', 2, 'Level-2. Cognitive Medical Assistant. ERROR 유발성 정신 오염 제어와 의료 장비 운용을 보조한다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_PHYSICIAN', '의사', 3, 'Level-3. Cognitive Physician. 진단, 처방, 작전 중 생체 항상성 유지 판단을 담당하는 실무 책임자다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_MEDICAL_PROFESSOR', '교수', 4, 'Level-4. Cognitive Medical Professor. 고위 의료 연구와 정신 오염 증상 자문을 담당하는 관리자급 의료 인원이다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'COGNITIVE_RECONSTRUCTION_MEDICAL_HEAD', '인지재구성의료부서장', 5, 'Level-5. Cognitive Reconstruction Medical Head. 인지재구성의료부서의 최고 책임자로 의료 정책과 특수 처치 승인을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'MD'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 인지재구성의료부서 고위 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'ALS'), 'ASSET_LOGISTICS_INTERN', '인턴', 0, 'Level-0. Asset Logistics Intern. 자산물류관리부의 보급 기록, 운송 문서, 창고 정리 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'ASSET_TRANSPORT_OPERATOR', '운송요원', 1, 'Level-1. Asset Transport Operator. 전략 자원과 군수 장비의 표준 물류 이동을 수행한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'SENIOR_ASSET_TRANSPORT_OPERATOR', '선임 운송요원', 2, 'Level-2. Senior Asset Transport Operator. ERROR 격리 자산 운송과 복합 보급 경로를 관리한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'ASSET_LOGISTICS_CONTROLLER', '물류 관제관', 3, 'Level-3. Asset Logistics Controller. 다중우주 물류 이동, 운송 우선순위, 보급 흐름을 관제한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'ASSET_SUPPLY_CHAIN_MANAGER', '공급망 관리자', 4, 'Level-4. Asset Supply Chain Manager. 휴면-널 인적 자원과 고위 자산 배분을 관리한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'ASSET_LOGISTICS_MANAGEMENT_HEAD', '자산물류관리부서장', 5, 'Level-5. Asset Logistics Management Head. 자산물류관리부의 최고 책임자로 자산 보급 정책을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'ALS'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 자산물류관리부 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'HM'), 'HYPER_PRODUCTION_INTERN', '생산 인턴', 0, 'Level-0. Hyper Production Intern. 하이퍼생산부서의 생산 기록 정리와 제조 공정 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'HYPER_MANUFACTURING_OPERATOR', '제조요원', 1, 'Level-1. Hyper Manufacturing Operator. 초차원 격리 설비 부품과 표준 제조 공정 운용을 수행한다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'SENIOR_HYPER_MANUFACTURING_OPERATOR', '선임 제조요원', 2, 'Level-2. Senior Hyper Manufacturing Operator. 메타 오염 방어 장구와 특수 물품 제조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'HYPER_PRODUCTION_PROCESS_SUPERVISOR', '생산공정 감독관', 3, 'Level-3. Hyper Production Process Supervisor. 결전 병기 물자 생산 공정과 작업 단위를 감독한다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'HYPER_PRODUCTION_MANAGER', '생산관리자', 4, 'Level-4. Hyper Production Manager. 하이퍼 생산 계획, 자재 배정, 공정 위험 관리를 담당한다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'HYPER_PRODUCTION_DEPARTMENT_HEAD', '하이퍼생산부서장', 5, 'Level-5. Hyper Production Department Head. 하이퍼생산부서의 최고 책임자로 생산 정책과 승인 권한을 가진다.'),
((SELECT id FROM departments WHERE code = 'HM'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 하이퍼생산부서 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'NIC'), 'NARRATIVE_RECORDS_INTERN', '서사기록 인턴', 0, 'Level-0. Narrative Records Intern. 서사 기록 정리와 심의 자료 보조를 담당한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'NARRATIVE_ASSESSOR', '서사감정관', 1, 'Level-1. Narrative Assessor. 서사 오염 여부와 기록 무결성 기초 판정을 수행한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'SENIOR_NARRATIVE_ASSESSOR', '상급 서사감정관', 2, 'Level-2. Senior Narrative Assessor. 복합 서사 사건과 인과 훼손 가능성을 분석한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'NARRATIVE_REVIEW_OFFICER', '서사심의관', 3, 'Level-3. Narrative Review Officer. 서사 조작, 실험 승인, 격리 기록 심의를 담당한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'INTEGRITY_MANAGER', '무결성관리관', 4, 'Level-4. Integrity Manager. Main Plot 보호와 서사 무결성 정책을 관리한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'NARRATIVE_INTEGRITY_CHAIR', '서사 무결성 위원장', 5, 'Level-5. Narrative Integrity Chair. 서사 무결성 위원회의 최고 책임자로 심의 권한을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'NIC'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 서사 무결성 사안의 최종 감독 권한을 가진다.'),

((SELECT id FROM departments WHERE code = 'TMD'), 'TIMELINE_OBSERVER', '시간선 관측관', 2, 'Level-2. Timeline Observer. 시간선 변동률과 관측 데이터를 기록하고 이상 상태를 보고한다.'),
((SELECT id FROM departments WHERE code = 'TMD'), 'TIMELINE_TEAM_LEAD', '시간선 팀장', 3, 'Level-3. Timeline Team Lead. 시간선 관측팀을 지휘하고 변동 대응 절차를 조율한다.'),
((SELECT id FROM departments WHERE code = 'TMD'), 'SUPERVISOR', '감독관', 4, 'Level-4. Supervisor. 시간선 관리 작전과 붕괴 가능성 평가를 감독한다.'),
((SELECT id FROM departments WHERE code = 'TMD'), 'TIMELINE_MANAGEMENT_HEAD', '시간선 관리부서장', 5, 'Level-5. Timeline Management Head. 시간선 관리부의 최고 책임자로 시간선 개입 정책을 총괄한다.'),
((SELECT id FROM departments WHERE code = 'TMD'), 'SENIOR_OVERWATCH_COMMANDER', '상급감시사령관', 6, 'Highest Supervisor. Senior Overwatch Commander. 시간선 관리 사안의 최종 감독 권한을 가진다.');
